insert into document_type (id, name, agenda_id) values (1, 'Mzdový list', 1);
insert into document_type (id, name, agenda_id) values (2, 'Docházka', 1);
insert into document_type (id, name, agenda_id) values (3, 'Exekuce', 1);
insert into document_type (id, name, agenda_id) values (4, 'Dohoda o srážkách', 1);
insert into document_type (id, name, agenda_id) values (5, 'Dohoda o bezhotovostní výplatě mzdy', 1);
insert into document_type (id, name, agenda_id) values (6, 'Čestné prohlášení', 2);
insert into document_type (id, name, agenda_id) values (7, 'Dohoda o hmotné zodpovědnosti', 2);
insert into document_type (id, name, agenda_id) values (8, 'Informace zaměstnanci', 2);
insert into document_type (id, name, agenda_id) values (9, 'Osobní dotazník', 2);
insert into document_type (id, name, agenda_id) values (10, 'Pracovní smlouva', 2);
insert into document_type (id, name, agenda_id) values (11, 'Souhlas o elektronickém podpisování', 2);
insert into document_type (id, name, agenda_id) values (12, 'Souhlas se pracováním osobních údajů', 2);
