insert into position (id, title, employee_id) values (1, 'Sociální pracovník', 671);
insert into position (id, title, employee_id) values (2, 'Sociální pracovník', 166);
insert into position (id, title, employee_id) values (3, 'Sociální pracovník', 407);
insert into position (id, title, employee_id) values (4, 'Vedoucí sekce rízení lidských zdrojů', 778);
insert into position (id, title, employee_id) values (5, 'Personalista', 528);
insert into position (id, title, employee_id) values (6, 'Sociální pracovník', 816);
insert into position (id, title, employee_id) values (7, 'Sociální pracovník', 169);
insert into position (id, title, employee_id) values (8, 'Sociální pracovník', 667);
insert into position (id, title, employee_id) values (9, 'Sociální pracovník', 394);
insert into position (id, title, employee_id) values (10, 'Sociální pracovník', 619);
insert into position (id, title, employee_id) values (11, 'Sociální pracovník', 662);
insert into position (id, title, employee_id) values (12, 'Sociální pracovník', 15);
insert into position (id, title, employee_id) values (13, 'Sociální pracovník', 912);
insert into position (id, title, employee_id) values (14, 'Sociální pracovník', 899);
insert into position (id, title, employee_id) values (15, 'Sociální pracovník', 991);
insert into position (id, title, employee_id) values (16, 'Sociální pracovník', 533);
insert into position (id, title, employee_id) values (17, 'Sociální pracovník', 335);
insert into position (id, title, employee_id) values (18, 'Sociální pracovník', 214);
insert into position (id, title, employee_id) values (19, 'Sociální pracovník', 118);
insert into position (id, title, employee_id) values (20, 'Sociální pracovník', 367);
insert into position (id, title, employee_id) values (21, 'Sociální pracovník', 343);
insert into position (id, title, employee_id) values (22, 'Sociální pracovník', 559);
insert into position (id, title, employee_id) values (23, 'Sociální pracovník', 997);
insert into position (id, title, employee_id) values (24, 'Správce IT', 73);
insert into position (id, title, employee_id) values (25, 'Sociální pracovník', 155);
insert into position (id, title, employee_id) values (26, 'Sociální pracovník', 470);
insert into position (id, title, employee_id) values (27, 'Sociální pracovník', 613);
insert into position (id, title, employee_id) values (28, 'Sociální pracovník', 671);
insert into position (id, title, employee_id) values (29, 'Sociální pracovník', 462);
insert into position (id, title, employee_id) values (30, 'Sociální pracovník', 348);
insert into position (id, title, employee_id) values (31, 'Vedoucí sekce rízení lidských zdrojů', 85);
insert into position (id, title, employee_id) values (32, 'Sociální pracovník', 151);
insert into position (id, title, employee_id) values (33, 'Sociální pracovník', 613);
insert into position (id, title, employee_id) values (34, 'Sociální pracovník', 907);
insert into position (id, title, employee_id) values (35, 'Sociální pracovník', 510);
insert into position (id, title, employee_id) values (36, 'Sociální pracovník', 414);
insert into position (id, title, employee_id) values (37, 'Sociální pracovník', 442);
insert into position (id, title, employee_id) values (38, 'Vedoucí sekce rízení lidských zdrojů', 798);
insert into position (id, title, employee_id) values (39, 'Sociální pracovník', 578);
insert into position (id, title, employee_id) values (40, 'Sociální pracovník', 478);
insert into position (id, title, employee_id) values (41, 'Manažer', 516);
insert into position (id, title, employee_id) values (42, 'Manažer', 712);
insert into position (id, title, employee_id) values (43, 'Sociální pracovník', 62);
insert into position (id, title, employee_id) values (44, 'Sociální pracovník', 163);
insert into position (id, title, employee_id) values (45, 'Vedoucí sekce rízení lidských zdrojů', 479);
insert into position (id, title, employee_id) values (46, 'Vedoucí sekce rízení lidských zdrojů', 264);
insert into position (id, title, employee_id) values (47, 'Sociální pracovník', 38);
insert into position (id, title, employee_id) values (48, 'Sociální pracovník', 660);
insert into position (id, title, employee_id) values (49, 'Sociální pracovník', 677);
insert into position (id, title, employee_id) values (50, 'Sociální pracovník', 50);
insert into position (id, title, employee_id) values (51, 'Sociální pracovník', 613);
insert into position (id, title, employee_id) values (52, 'Sociální pracovník', 76);
insert into position (id, title, employee_id) values (53, 'Sociální pracovník', 444);
insert into position (id, title, employee_id) values (54, 'Sociální pracovník', 199);
insert into position (id, title, employee_id) values (55, 'Sociální pracovník', 401);
insert into position (id, title, employee_id) values (56, 'Sociální pracovník', 179);
insert into position (id, title, employee_id) values (57, 'Sociální pracovník', 912);
insert into position (id, title, employee_id) values (58, 'Sociální pracovník', 2);
insert into position (id, title, employee_id) values (59, 'Sociální pracovník', 183);
insert into position (id, title, employee_id) values (60, 'Sociální pracovník', 815);
insert into position (id, title, employee_id) values (61, 'Sociální pracovník', 752);
insert into position (id, title, employee_id) values (62, 'Sociální pracovník', 686);
insert into position (id, title, employee_id) values (63, 'Sociální pracovník', 947);
insert into position (id, title, employee_id) values (64, 'Sociální pracovník', 684);
insert into position (id, title, employee_id) values (65, 'Sociální pracovník', 855);
insert into position (id, title, employee_id) values (66, 'Sociální pracovník', 522);
insert into position (id, title, employee_id) values (67, 'Vedoucí sekce rízení lidských zdrojů', 516);
insert into position (id, title, employee_id) values (68, 'Sociální pracovník', 867);
insert into position (id, title, employee_id) values (69, 'Psychiatr', 971);
insert into position (id, title, employee_id) values (70, 'Sociální pracovník', 47);
insert into position (id, title, employee_id) values (71, 'Sociální pracovník', 781);
insert into position (id, title, employee_id) values (72, 'Psychiatr', 305);
insert into position (id, title, employee_id) values (73, 'Sociální pracovník', 504);
insert into position (id, title, employee_id) values (74, 'Sociální pracovník', 860);
insert into position (id, title, employee_id) values (75, 'Sociální pracovník', 272);
insert into position (id, title, employee_id) values (76, 'Psychiatr', 461);
insert into position (id, title, employee_id) values (77, 'Sociální pracovník', 431);
insert into position (id, title, employee_id) values (78, 'Sociální pracovník', 172);
insert into position (id, title, employee_id) values (79, 'Sociální pracovník', 391);
insert into position (id, title, employee_id) values (80, 'Sociální pracovník', 983);
insert into position (id, title, employee_id) values (81, 'Sociální pracovník', 836);
insert into position (id, title, employee_id) values (82, 'Sociální pracovník', 144);
insert into position (id, title, employee_id) values (83, 'Sociální pracovník', 947);
insert into position (id, title, employee_id) values (84, 'Sociální pracovník', 232);
insert into position (id, title, employee_id) values (85, 'Sociální pracovník', 727);
insert into position (id, title, employee_id) values (86, 'Sociální pracovník', 243);
insert into position (id, title, employee_id) values (87, 'Sociální pracovník', 550);
insert into position (id, title, employee_id) values (88, 'Sociální pracovník', 307);
insert into position (id, title, employee_id) values (89, 'Sociální pracovník', 534);
insert into position (id, title, employee_id) values (90, 'Sociální pracovník', 591);
insert into position (id, title, employee_id) values (91, 'Sociální pracovník', 465);
insert into position (id, title, employee_id) values (92, 'Sociální pracovník', 138);
insert into position (id, title, employee_id) values (93, 'Sociální pracovník', 699);
insert into position (id, title, employee_id) values (94, 'Sociální pracovník', 781);
insert into position (id, title, employee_id) values (95, 'Sociální pracovník', 268);
insert into position (id, title, employee_id) values (96, 'Správce IT', 393);
insert into position (id, title, employee_id) values (97, 'Vedoucí sekce rízení lidských zdrojů', 608);
insert into position (id, title, employee_id) values (98, 'Vedoucí sekce rízení lidských zdrojů', 767);
insert into position (id, title, employee_id) values (99, 'Sociální pracovník', 665);
insert into position (id, title, employee_id) values (100, 'Sociální pracovník', 743);
insert into position (id, title, employee_id) values (101, 'Personalista', 91);
insert into position (id, title, employee_id) values (102, 'Sociální pracovník', 841);
insert into position (id, title, employee_id) values (103, 'Sociální pracovník', 821);
insert into position (id, title, employee_id) values (104, 'Vedoucí sekce rízení lidských zdrojů', 340);
insert into position (id, title, employee_id) values (105, 'Sociální pracovník', 746);
insert into position (id, title, employee_id) values (106, 'Sociální pracovník', 2);
insert into position (id, title, employee_id) values (107, 'Sociální pracovník', 428);
insert into position (id, title, employee_id) values (108, 'Sociální pracovník', 154);
insert into position (id, title, employee_id) values (109, 'Manažer', 797);
insert into position (id, title, employee_id) values (110, 'Sociální pracovník', 759);
insert into position (id, title, employee_id) values (111, 'Sociální pracovník', 157);
insert into position (id, title, employee_id) values (112, 'Sociální pracovník', 879);
insert into position (id, title, employee_id) values (113, 'Sociální pracovník', 854);
insert into position (id, title, employee_id) values (114, 'Sociální pracovník', 756);
insert into position (id, title, employee_id) values (115, 'Sociální pracovník', 260);
insert into position (id, title, employee_id) values (116, 'Sociální pracovník', 967);
insert into position (id, title, employee_id) values (117, 'Sociální pracovník', 232);
insert into position (id, title, employee_id) values (118, 'Sociální pracovník', 267);
insert into position (id, title, employee_id) values (119, 'Sociální pracovník', 708);
insert into position (id, title, employee_id) values (120, 'Sociální pracovník', 251);
insert into position (id, title, employee_id) values (121, 'Sociální pracovník', 749);
insert into position (id, title, employee_id) values (122, 'Sociální pracovník', 629);
insert into position (id, title, employee_id) values (123, 'Sociální pracovník', 127);
insert into position (id, title, employee_id) values (124, 'Sociální pracovník', 741);
insert into position (id, title, employee_id) values (125, 'Manažer', 667);
insert into position (id, title, employee_id) values (126, 'Sociální pracovník', 509);
insert into position (id, title, employee_id) values (127, 'Sociální pracovník', 468);
insert into position (id, title, employee_id) values (128, 'Sociální pracovník', 717);
insert into position (id, title, employee_id) values (129, 'Pracovník v sociálních službách', 350);
insert into position (id, title, employee_id) values (130, 'Pracovník v sociálních službách', 201);
insert into position (id, title, employee_id) values (131, 'Sociální pracovník', 467);
insert into position (id, title, employee_id) values (132, 'Sociální pracovník', 19);
insert into position (id, title, employee_id) values (133, 'Sociální pracovník', 385);
insert into position (id, title, employee_id) values (134, 'Sociální pracovník', 35);
insert into position (id, title, employee_id) values (135, 'Psychiatr', 726);
insert into position (id, title, employee_id) values (136, 'Sociální pracovník', 750);
insert into position (id, title, employee_id) values (137, 'Sociální pracovník', 944);
insert into position (id, title, employee_id) values (138, 'Správce IT', 399);
insert into position (id, title, employee_id) values (139, 'Sociální pracovník', 454);
insert into position (id, title, employee_id) values (140, 'Sociální pracovník', 446);
insert into position (id, title, employee_id) values (141, 'Sociální pracovník', 143);
insert into position (id, title, employee_id) values (142, 'Sociální pracovník', 856);
insert into position (id, title, employee_id) values (143, 'Psychiatr', 388);
insert into position (id, title, employee_id) values (144, 'Správce IT', 484);
insert into position (id, title, employee_id) values (145, 'Sociální pracovník', 133);
insert into position (id, title, employee_id) values (146, 'Sociální pracovník', 873);
insert into position (id, title, employee_id) values (147, 'Sociální pracovník', 78);
insert into position (id, title, employee_id) values (148, 'Pracovník v sociálních službách', 132);
insert into position (id, title, employee_id) values (149, 'Sociální pracovník', 358);
insert into position (id, title, employee_id) values (150, 'Sociální pracovník', 299);
insert into position (id, title, employee_id) values (151, 'Sociální pracovník', 762);
insert into position (id, title, employee_id) values (152, 'Manažer', 452);
insert into position (id, title, employee_id) values (153, 'Sociální pracovník', 313);
insert into position (id, title, employee_id) values (154, 'Sociální pracovník', 852);
insert into position (id, title, employee_id) values (155, 'Sociální pracovník', 49);
insert into position (id, title, employee_id) values (156, 'Sociální pracovník', 616);
insert into position (id, title, employee_id) values (157, 'Sociální pracovník', 888);
insert into position (id, title, employee_id) values (158, 'Sociální pracovník', 75);
insert into position (id, title, employee_id) values (159, 'Sociální pracovník', 141);
insert into position (id, title, employee_id) values (160, 'Sociální pracovník', 694);
insert into position (id, title, employee_id) values (161, 'Sociální pracovník', 874);
insert into position (id, title, employee_id) values (162, 'Sociální pracovník', 6);
insert into position (id, title, employee_id) values (163, 'Pracovník v sociálních službách', 980);
insert into position (id, title, employee_id) values (164, 'Sociální pracovník', 30);
insert into position (id, title, employee_id) values (165, 'Sociální pracovník', 120);
insert into position (id, title, employee_id) values (166, 'Sociální pracovník', 160);
insert into position (id, title, employee_id) values (167, 'Sociální pracovník', 607);
insert into position (id, title, employee_id) values (168, 'Správce IT', 625);
insert into position (id, title, employee_id) values (169, 'Sociální pracovník', 706);
insert into position (id, title, employee_id) values (170, 'Sociální pracovník', 657);
insert into position (id, title, employee_id) values (171, 'Sociální pracovník', 222);
insert into position (id, title, employee_id) values (172, 'Sociální pracovník', 701);
insert into position (id, title, employee_id) values (173, 'Sociální pracovník', 44);
insert into position (id, title, employee_id) values (174, 'Pracovník v sociálních službách', 176);
insert into position (id, title, employee_id) values (175, 'Sociální pracovník', 479);
insert into position (id, title, employee_id) values (176, 'Sociální pracovník', 328);
insert into position (id, title, employee_id) values (177, 'Sociální pracovník', 592);
insert into position (id, title, employee_id) values (178, 'Sociální pracovníkVšeobecná sestra', 782);
insert into position (id, title, employee_id) values (179, 'Sociální pracovník', 160);
insert into position (id, title, employee_id) values (180, 'Sociální pracovník', 676);
insert into position (id, title, employee_id) values (181, 'Sociální pracovník', 797);
insert into position (id, title, employee_id) values (182, 'Sociální pracovník', 790);
insert into position (id, title, employee_id) values (183, 'Sociální pracovník', 571);
insert into position (id, title, employee_id) values (184, 'Sociální pracovník', 486);
insert into position (id, title, employee_id) values (185, 'Sociální pracovník', 408);
insert into position (id, title, employee_id) values (186, 'Sociální pracovník', 383);
insert into position (id, title, employee_id) values (187, 'Sociální pracovníkVšeobecná sestra', 222);
insert into position (id, title, employee_id) values (188, 'Sociální pracovník', 546);
insert into position (id, title, employee_id) values (189, 'Sociální pracovník', 486);
insert into position (id, title, employee_id) values (190, 'Sociální pracovník', 666);
insert into position (id, title, employee_id) values (191, 'Sociální pracovník', 468);
insert into position (id, title, employee_id) values (192, 'Sociální pracovník', 559);
insert into position (id, title, employee_id) values (193, 'Sociální pracovník', 773);
insert into position (id, title, employee_id) values (194, 'Manažer', 646);
insert into position (id, title, employee_id) values (195, 'Sociální pracovník', 345);
insert into position (id, title, employee_id) values (196, 'Sociální pracovník', 156);
insert into position (id, title, employee_id) values (197, 'Sociální pracovník', 246);
insert into position (id, title, employee_id) values (198, 'Správce IT', 470);
insert into position (id, title, employee_id) values (199, 'Sociální pracovník', 492);
insert into position (id, title, employee_id) values (200, 'Sociální pracovník', 370);
insert into position (id, title, employee_id) values (201, 'Vedoucí sekce rízení lidských zdrojů', 846);
insert into position (id, title, employee_id) values (202, 'Sociální pracovník', 873);
insert into position (id, title, employee_id) values (203, 'Sociální pracovník', 382);
insert into position (id, title, employee_id) values (204, 'Sociální pracovník', 115);
insert into position (id, title, employee_id) values (205, 'Sociální pracovník', 959);
insert into position (id, title, employee_id) values (206, 'Sociální pracovník', 957);
insert into position (id, title, employee_id) values (207, 'Sociální pracovník', 64);
insert into position (id, title, employee_id) values (208, 'Sociální pracovník', 582);
insert into position (id, title, employee_id) values (209, 'Sociální pracovník', 494);
insert into position (id, title, employee_id) values (210, 'Sociální pracovník', 265);
insert into position (id, title, employee_id) values (211, 'Sociální pracovník', 965);
insert into position (id, title, employee_id) values (212, 'Personalista', 668);
insert into position (id, title, employee_id) values (213, 'Sociální pracovník', 660);
insert into position (id, title, employee_id) values (214, 'Vedoucí sekce rízení lidských zdrojů', 410);
insert into position (id, title, employee_id) values (215, 'Sociální pracovník', 399);
insert into position (id, title, employee_id) values (216, 'Správce IT', 736);
insert into position (id, title, employee_id) values (217, 'Vedoucí sekce rízení lidských zdrojů', 520);
insert into position (id, title, employee_id) values (218, 'Sociální pracovník', 720);
insert into position (id, title, employee_id) values (219, 'Sociální pracovníkVšeobecná sestra', 473);
insert into position (id, title, employee_id) values (220, 'Sociální pracovník', 12);
insert into position (id, title, employee_id) values (221, 'Sociální pracovník', 922);
insert into position (id, title, employee_id) values (222, 'Sociální pracovník', 843);
insert into position (id, title, employee_id) values (223, 'Sociální pracovníkVšeobecná sestra', 349);
insert into position (id, title, employee_id) values (224, 'Sociální pracovník', 35);
insert into position (id, title, employee_id) values (225, 'Manažer', 114);
insert into position (id, title, employee_id) values (226, 'Sociální pracovník', 108);
insert into position (id, title, employee_id) values (227, 'Sociální pracovník', 818);
insert into position (id, title, employee_id) values (228, 'Správce IT', 849);
insert into position (id, title, employee_id) values (229, 'Sociální pracovník', 727);
insert into position (id, title, employee_id) values (230, 'Sociální pracovník', 325);
insert into position (id, title, employee_id) values (231, 'Sociální pracovník', 368);
insert into position (id, title, employee_id) values (232, 'Sociální pracovník', 551);
insert into position (id, title, employee_id) values (233, 'Sociální pracovník', 484);
insert into position (id, title, employee_id) values (234, 'Sociální pracovník', 980);
insert into position (id, title, employee_id) values (235, 'Sociální pracovník', 635);
insert into position (id, title, employee_id) values (236, 'Sociální pracovník', 334);
insert into position (id, title, employee_id) values (237, 'Sociální pracovník', 761);
insert into position (id, title, employee_id) values (238, 'Pracovník v sociálních službách', 568);
insert into position (id, title, employee_id) values (239, 'Sociální pracovník', 31);
insert into position (id, title, employee_id) values (240, 'Sociální pracovník', 923);
insert into position (id, title, employee_id) values (241, 'Sociální pracovník', 84);
insert into position (id, title, employee_id) values (242, 'Sociální pracovník', 447);
insert into position (id, title, employee_id) values (243, 'Psychiatr', 85);
insert into position (id, title, employee_id) values (244, 'Sociální pracovník', 454);
insert into position (id, title, employee_id) values (245, 'Psychiatr', 150);
insert into position (id, title, employee_id) values (246, 'Sociální pracovník', 681);
insert into position (id, title, employee_id) values (247, 'Sociální pracovník', 393);
insert into position (id, title, employee_id) values (248, 'Sociální pracovník', 436);
insert into position (id, title, employee_id) values (249, 'Sociální pracovník', 299);
insert into position (id, title, employee_id) values (250, 'Sociální pracovník', 670);
insert into position (id, title, employee_id) values (251, 'Sociální pracovník', 395);
insert into position (id, title, employee_id) values (252, 'Sociální pracovník', 699);
insert into position (id, title, employee_id) values (253, 'Pracovník v sociálních službách', 197);
insert into position (id, title, employee_id) values (254, 'Sociální pracovník', 371);
insert into position (id, title, employee_id) values (255, 'Sociální pracovník', 160);
insert into position (id, title, employee_id) values (256, 'Sociální pracovník', 75);
insert into position (id, title, employee_id) values (257, 'Sociální pracovník', 545);
insert into position (id, title, employee_id) values (258, 'Sociální pracovník', 456);
insert into position (id, title, employee_id) values (259, 'Sociální pracovník', 339);
insert into position (id, title, employee_id) values (260, 'Sociální pracovník', 736);
insert into position (id, title, employee_id) values (261, 'Pracovník v sociálních službách', 138);
insert into position (id, title, employee_id) values (262, 'Sociální pracovník', 324);
insert into position (id, title, employee_id) values (263, 'Vedoucí sekce rízení lidských zdrojů', 924);
insert into position (id, title, employee_id) values (264, 'Personalista', 489);
insert into position (id, title, employee_id) values (265, 'Sociální pracovník', 750);
insert into position (id, title, employee_id) values (266, 'Personalista', 539);
insert into position (id, title, employee_id) values (267, 'Sociální pracovník', 214);
insert into position (id, title, employee_id) values (268, 'Správce IT', 24);
insert into position (id, title, employee_id) values (269, 'Sociální pracovník', 516);
insert into position (id, title, employee_id) values (270, 'Sociální pracovník', 527);
insert into position (id, title, employee_id) values (271, 'Sociální pracovník', 732);
insert into position (id, title, employee_id) values (272, 'Sociální pracovník', 962);
insert into position (id, title, employee_id) values (273, 'Personalista', 126);
insert into position (id, title, employee_id) values (274, 'Sociální pracovník', 115);
insert into position (id, title, employee_id) values (275, 'Sociální pracovník', 676);
insert into position (id, title, employee_id) values (276, 'Psychiatr', 215);
insert into position (id, title, employee_id) values (277, 'Sociální pracovník', 338);
insert into position (id, title, employee_id) values (278, 'Vedoucí sekce rízení lidských zdrojů', 216);
insert into position (id, title, employee_id) values (279, 'Sociální pracovník', 680);
insert into position (id, title, employee_id) values (280, 'Sociální pracovník', 445);
insert into position (id, title, employee_id) values (281, 'Sociální pracovník', 348);
insert into position (id, title, employee_id) values (282, 'Sociální pracovník', 747);
insert into position (id, title, employee_id) values (283, 'Sociální pracovník', 87);
insert into position (id, title, employee_id) values (284, 'Pracovník v sociálních službách', 44);
insert into position (id, title, employee_id) values (285, 'Sociální pracovník', 13);
insert into position (id, title, employee_id) values (286, 'Sociální pracovník', 793);
insert into position (id, title, employee_id) values (287, 'Sociální pracovník', 939);
insert into position (id, title, employee_id) values (288, 'Sociální pracovník', 538);
insert into position (id, title, employee_id) values (289, 'Sociální pracovník', 671);
insert into position (id, title, employee_id) values (290, 'Pracovník v sociálních službách', 189);
insert into position (id, title, employee_id) values (291, 'Manažer', 506);
insert into position (id, title, employee_id) values (292, 'Sociální pracovník', 261);
insert into position (id, title, employee_id) values (293, 'Pracovník v sociálních službách', 113);
insert into position (id, title, employee_id) values (294, 'Sociální pracovník', 809);
insert into position (id, title, employee_id) values (295, 'Sociální pracovník', 372);
insert into position (id, title, employee_id) values (296, 'Sociální pracovník', 103);
insert into position (id, title, employee_id) values (297, 'Sociální pracovník', 175);
insert into position (id, title, employee_id) values (298, 'Sociální pracovníkVšeobecná sestra', 100);
insert into position (id, title, employee_id) values (299, 'Sociální pracovník', 924);
insert into position (id, title, employee_id) values (300, 'Pracovník v sociálních službách', 928);
insert into position (id, title, employee_id) values (301, 'Sociální pracovník', 196);
insert into position (id, title, employee_id) values (302, 'Sociální pracovník', 52);
insert into position (id, title, employee_id) values (303, 'Pracovník v sociálních službách', 952);
insert into position (id, title, employee_id) values (304, 'Sociální pracovník', 701);
insert into position (id, title, employee_id) values (305, 'Správce IT', 926);
insert into position (id, title, employee_id) values (306, 'Sociální pracovník', 154);
insert into position (id, title, employee_id) values (307, 'Sociální pracovník', 211);
insert into position (id, title, employee_id) values (308, 'Sociální pracovník', 128);
insert into position (id, title, employee_id) values (309, 'Sociální pracovník', 374);
insert into position (id, title, employee_id) values (310, 'Sociální pracovník', 129);
insert into position (id, title, employee_id) values (311, 'Sociální pracovník', 533);
insert into position (id, title, employee_id) values (312, 'Sociální pracovník', 805);
insert into position (id, title, employee_id) values (313, 'Sociální pracovník', 15);
insert into position (id, title, employee_id) values (314, 'Sociální pracovník', 922);
insert into position (id, title, employee_id) values (315, 'Sociální pracovník', 363);
insert into position (id, title, employee_id) values (316, 'Sociální pracovník', 651);
insert into position (id, title, employee_id) values (317, 'Sociální pracovník', 316);
insert into position (id, title, employee_id) values (318, 'Sociální pracovník', 800);
insert into position (id, title, employee_id) values (319, 'Sociální pracovník', 552);
insert into position (id, title, employee_id) values (320, 'Sociální pracovník', 433);
insert into position (id, title, employee_id) values (321, 'Správce IT', 979);
insert into position (id, title, employee_id) values (322, 'Sociální pracovník', 920);
insert into position (id, title, employee_id) values (323, 'Vedoucí sekce rízení lidských zdrojů', 749);
insert into position (id, title, employee_id) values (324, 'Sociální pracovník', 373);
insert into position (id, title, employee_id) values (325, 'Správce IT', 295);
insert into position (id, title, employee_id) values (326, 'Sociální pracovník', 161);
insert into position (id, title, employee_id) values (327, 'Sociální pracovník', 962);
insert into position (id, title, employee_id) values (328, 'Sociální pracovník', 491);
insert into position (id, title, employee_id) values (329, 'Personalista', 109);
insert into position (id, title, employee_id) values (330, 'Sociální pracovník', 968);
insert into position (id, title, employee_id) values (331, 'Psychiatr', 960);
insert into position (id, title, employee_id) values (332, 'Sociální pracovník', 626);
insert into position (id, title, employee_id) values (333, 'Vedoucí sekce rízení lidských zdrojů', 860);
insert into position (id, title, employee_id) values (334, 'Sociální pracovník', 894);
insert into position (id, title, employee_id) values (335, 'Sociální pracovník', 460);
insert into position (id, title, employee_id) values (336, 'Personalista', 568);
insert into position (id, title, employee_id) values (337, 'Sociální pracovník', 669);
insert into position (id, title, employee_id) values (338, 'Sociální pracovník', 916);
insert into position (id, title, employee_id) values (339, 'Sociální pracovník', 180);
insert into position (id, title, employee_id) values (340, 'Sociální pracovník', 924);
insert into position (id, title, employee_id) values (341, 'Sociální pracovník', 843);
insert into position (id, title, employee_id) values (342, 'Sociální pracovník', 354);
insert into position (id, title, employee_id) values (343, 'Sociální pracovník', 836);
insert into position (id, title, employee_id) values (344, 'Personalista', 463);
insert into position (id, title, employee_id) values (345, 'Sociální pracovník', 119);
insert into position (id, title, employee_id) values (346, 'Sociální pracovník', 524);
insert into position (id, title, employee_id) values (347, 'Sociální pracovník', 460);
insert into position (id, title, employee_id) values (348, 'Sociální pracovník', 937);
insert into position (id, title, employee_id) values (349, 'Sociální pracovník', 264);
insert into position (id, title, employee_id) values (350, 'Sociální pracovník', 511);
insert into position (id, title, employee_id) values (351, 'Správce IT', 976);
insert into position (id, title, employee_id) values (352, 'Vedoucí sekce rízení lidských zdrojů', 69);
insert into position (id, title, employee_id) values (353, 'Sociální pracovník', 593);
insert into position (id, title, employee_id) values (354, 'Sociální pracovník', 148);
insert into position (id, title, employee_id) values (355, 'Sociální pracovník', 148);
insert into position (id, title, employee_id) values (356, 'Sociální pracovník', 579);
insert into position (id, title, employee_id) values (357, 'Sociální pracovník', 821);
insert into position (id, title, employee_id) values (358, 'Správce IT', 297);
insert into position (id, title, employee_id) values (359, 'Sociální pracovník', 383);
insert into position (id, title, employee_id) values (360, 'Sociální pracovník', 268);
insert into position (id, title, employee_id) values (361, 'Vedoucí sekce rízení lidských zdrojů', 290);
insert into position (id, title, employee_id) values (362, 'Sociální pracovník', 818);
insert into position (id, title, employee_id) values (363, 'Sociální pracovník', 387);
insert into position (id, title, employee_id) values (364, 'Sociální pracovník', 236);
insert into position (id, title, employee_id) values (365, 'Vedoucí sekce rízení lidských zdrojů', 212);
insert into position (id, title, employee_id) values (366, 'Sociální pracovník', 122);
insert into position (id, title, employee_id) values (367, 'Sociální pracovník', 578);
insert into position (id, title, employee_id) values (368, 'Sociální pracovník', 24);
insert into position (id, title, employee_id) values (369, 'Sociální pracovníkVšeobecná sestra', 469);
insert into position (id, title, employee_id) values (370, 'Sociální pracovník', 830);
insert into position (id, title, employee_id) values (371, 'Sociální pracovník', 352);
insert into position (id, title, employee_id) values (372, 'Sociální pracovník', 801);
insert into position (id, title, employee_id) values (373, 'Sociální pracovník', 507);
insert into position (id, title, employee_id) values (374, 'Sociální pracovník', 162);
insert into position (id, title, employee_id) values (375, 'Sociální pracovník', 289);
insert into position (id, title, employee_id) values (376, 'Sociální pracovník', 566);
insert into position (id, title, employee_id) values (377, 'Sociální pracovník', 557);
insert into position (id, title, employee_id) values (378, 'Sociální pracovník', 58);
insert into position (id, title, employee_id) values (379, 'Sociální pracovník', 683);
insert into position (id, title, employee_id) values (380, 'Sociální pracovník', 153);
insert into position (id, title, employee_id) values (381, 'Sociální pracovník', 79);
insert into position (id, title, employee_id) values (382, 'Sociální pracovník', 764);
insert into position (id, title, employee_id) values (383, 'Sociální pracovník', 213);
insert into position (id, title, employee_id) values (384, 'Manažer', 910);
insert into position (id, title, employee_id) values (385, 'Sociální pracovník', 396);
insert into position (id, title, employee_id) values (386, 'Sociální pracovník', 599);
insert into position (id, title, employee_id) values (387, 'Sociální pracovník', 147);
insert into position (id, title, employee_id) values (388, 'Sociální pracovník', 368);
insert into position (id, title, employee_id) values (389, 'Sociální pracovník', 41);
insert into position (id, title, employee_id) values (390, 'Personalista', 550);
insert into position (id, title, employee_id) values (391, 'Sociální pracovník', 331);
insert into position (id, title, employee_id) values (392, 'Sociální pracovník', 812);
insert into position (id, title, employee_id) values (393, 'Sociální pracovník', 390);
insert into position (id, title, employee_id) values (394, 'Sociální pracovník', 599);
insert into position (id, title, employee_id) values (395, 'Sociální pracovník', 22);
insert into position (id, title, employee_id) values (396, 'Sociální pracovník', 919);
insert into position (id, title, employee_id) values (397, 'Sociální pracovníkVšeobecná sestra', 530);
insert into position (id, title, employee_id) values (398, 'Sociální pracovník', 614);
insert into position (id, title, employee_id) values (399, 'Sociální pracovník', 613);
insert into position (id, title, employee_id) values (400, 'Sociální pracovník', 801);
insert into position (id, title, employee_id) values (401, 'Sociální pracovník', 451);
insert into position (id, title, employee_id) values (402, 'Sociální pracovník', 408);
insert into position (id, title, employee_id) values (403, 'Sociální pracovník', 740);
insert into position (id, title, employee_id) values (404, 'Sociální pracovník', 64);
insert into position (id, title, employee_id) values (405, 'Sociální pracovník', 175);
insert into position (id, title, employee_id) values (406, 'Sociální pracovník', 67);
insert into position (id, title, employee_id) values (407, 'Pracovník v sociálních službách', 80);
insert into position (id, title, employee_id) values (408, 'Sociální pracovník', 900);
insert into position (id, title, employee_id) values (409, 'Sociální pracovník', 45);
insert into position (id, title, employee_id) values (410, 'Sociální pracovník', 666);
insert into position (id, title, employee_id) values (411, 'Psychiatr', 156);
insert into position (id, title, employee_id) values (412, 'Sociální pracovník', 309);
insert into position (id, title, employee_id) values (413, 'Psychiatr', 667);
insert into position (id, title, employee_id) values (414, 'Sociální pracovník', 636);
insert into position (id, title, employee_id) values (415, 'Pracovník v sociálních službách', 220);
insert into position (id, title, employee_id) values (416, 'Sociální pracovník', 917);
insert into position (id, title, employee_id) values (417, 'Sociální pracovník', 500);
insert into position (id, title, employee_id) values (418, 'Sociální pracovník', 70);
insert into position (id, title, employee_id) values (419, 'Sociální pracovník', 311);
insert into position (id, title, employee_id) values (420, 'Sociální pracovníkVšeobecná sestra', 832);
insert into position (id, title, employee_id) values (421, 'Sociální pracovník', 162);
insert into position (id, title, employee_id) values (422, 'Sociální pracovník', 296);
insert into position (id, title, employee_id) values (423, 'Sociální pracovník', 382);
insert into position (id, title, employee_id) values (424, 'Správce IT', 219);
insert into position (id, title, employee_id) values (425, 'Sociální pracovník', 637);
insert into position (id, title, employee_id) values (426, 'Sociální pracovník', 613);
insert into position (id, title, employee_id) values (427, 'Psychiatr', 69);
insert into position (id, title, employee_id) values (428, 'Personalista', 492);
insert into position (id, title, employee_id) values (429, 'Sociální pracovník', 50);
insert into position (id, title, employee_id) values (430, 'Sociální pracovník', 715);
insert into position (id, title, employee_id) values (431, 'Sociální pracovník', 170);
insert into position (id, title, employee_id) values (432, 'Sociální pracovník', 324);
insert into position (id, title, employee_id) values (433, 'Sociální pracovník', 292);
insert into position (id, title, employee_id) values (434, 'Sociální pracovník', 408);
insert into position (id, title, employee_id) values (435, 'Sociální pracovník', 719);
insert into position (id, title, employee_id) values (436, 'Sociální pracovník', 458);
insert into position (id, title, employee_id) values (437, 'Sociální pracovník', 518);
insert into position (id, title, employee_id) values (438, 'Sociální pracovník', 58);
insert into position (id, title, employee_id) values (439, 'Sociální pracovník', 71);
insert into position (id, title, employee_id) values (440, 'Sociální pracovník', 986);
insert into position (id, title, employee_id) values (441, 'Sociální pracovník', 589);
insert into position (id, title, employee_id) values (442, 'Sociální pracovník', 656);
insert into position (id, title, employee_id) values (443, 'Sociální pracovník', 662);
insert into position (id, title, employee_id) values (444, 'Sociální pracovník', 795);
insert into position (id, title, employee_id) values (445, 'Sociální pracovník', 989);
insert into position (id, title, employee_id) values (446, 'Sociální pracovník', 376);
insert into position (id, title, employee_id) values (447, 'Sociální pracovník', 354);
insert into position (id, title, employee_id) values (448, 'Sociální pracovník', 869);
insert into position (id, title, employee_id) values (449, 'Sociální pracovník', 895);
insert into position (id, title, employee_id) values (450, 'Sociální pracovník', 829);
insert into position (id, title, employee_id) values (451, 'Sociální pracovník', 937);
insert into position (id, title, employee_id) values (452, 'Sociální pracovník', 674);
insert into position (id, title, employee_id) values (453, 'Sociální pracovník', 678);
insert into position (id, title, employee_id) values (454, 'Sociální pracovník', 146);
insert into position (id, title, employee_id) values (455, 'Sociální pracovník', 130);
insert into position (id, title, employee_id) values (456, 'Sociální pracovník', 613);
insert into position (id, title, employee_id) values (457, 'Sociální pracovník', 146);
insert into position (id, title, employee_id) values (458, 'Sociální pracovník', 977);
insert into position (id, title, employee_id) values (459, 'Sociální pracovník', 847);
insert into position (id, title, employee_id) values (460, 'Sociální pracovník', 313);
insert into position (id, title, employee_id) values (461, 'Sociální pracovník', 697);
insert into position (id, title, employee_id) values (462, 'Sociální pracovník', 696);
insert into position (id, title, employee_id) values (463, 'Sociální pracovník', 612);
insert into position (id, title, employee_id) values (464, 'Sociální pracovník', 863);
insert into position (id, title, employee_id) values (465, 'Sociální pracovník', 392);
insert into position (id, title, employee_id) values (466, 'Sociální pracovník', 879);
insert into position (id, title, employee_id) values (467, 'Pracovník v sociálních službách', 763);
insert into position (id, title, employee_id) values (468, 'Sociální pracovník', 365);
insert into position (id, title, employee_id) values (469, 'Manažer', 9);
insert into position (id, title, employee_id) values (470, 'Manažer', 15);
insert into position (id, title, employee_id) values (471, 'Sociální pracovník', 949);
insert into position (id, title, employee_id) values (472, 'Sociální pracovník', 811);
insert into position (id, title, employee_id) values (473, 'Sociální pracovník', 231);
insert into position (id, title, employee_id) values (474, 'Personalista', 101);
insert into position (id, title, employee_id) values (475, 'Správce IT', 687);
insert into position (id, title, employee_id) values (476, 'Sociální pracovník', 647);
insert into position (id, title, employee_id) values (477, 'Manažer', 476);
insert into position (id, title, employee_id) values (478, 'Sociální pracovník', 2);
insert into position (id, title, employee_id) values (479, 'Sociální pracovník', 724);
insert into position (id, title, employee_id) values (480, 'Sociální pracovník', 393);
insert into position (id, title, employee_id) values (481, 'Sociální pracovník', 907);
insert into position (id, title, employee_id) values (482, 'Sociální pracovník', 115);
insert into position (id, title, employee_id) values (483, 'Sociální pracovník', 296);
insert into position (id, title, employee_id) values (484, 'Sociální pracovník', 871);
insert into position (id, title, employee_id) values (485, 'Sociální pracovník', 632);
insert into position (id, title, employee_id) values (486, 'Sociální pracovník', 628);
insert into position (id, title, employee_id) values (487, 'Sociální pracovník', 535);
insert into position (id, title, employee_id) values (488, 'Sociální pracovník', 111);
insert into position (id, title, employee_id) values (489, 'Sociální pracovník', 580);
insert into position (id, title, employee_id) values (490, 'Sociální pracovník', 324);
insert into position (id, title, employee_id) values (491, 'Sociální pracovník', 188);
insert into position (id, title, employee_id) values (492, 'Sociální pracovník', 701);
insert into position (id, title, employee_id) values (493, 'Sociální pracovník', 277);
insert into position (id, title, employee_id) values (494, 'Sociální pracovník', 858);
insert into position (id, title, employee_id) values (495, 'Sociální pracovník', 129);
insert into position (id, title, employee_id) values (496, 'Sociální pracovník', 240);
insert into position (id, title, employee_id) values (497, 'Sociální pracovník', 312);
insert into position (id, title, employee_id) values (498, 'Sociální pracovník', 807);
insert into position (id, title, employee_id) values (499, 'Personalista', 838);
insert into position (id, title, employee_id) values (500, 'Sociální pracovník', 939);
insert into position (id, title, employee_id) values (501, 'Sociální pracovník', 650);
insert into position (id, title, employee_id) values (502, 'Sociální pracovník', 832);
insert into position (id, title, employee_id) values (503, 'Sociální pracovník', 467);
insert into position (id, title, employee_id) values (504, 'Sociální pracovníkVšeobecná sestra', 325);
insert into position (id, title, employee_id) values (505, 'Sociální pracovník', 791);
insert into position (id, title, employee_id) values (506, 'Sociální pracovník', 562);
insert into position (id, title, employee_id) values (507, 'Sociální pracovník', 250);
insert into position (id, title, employee_id) values (508, 'Sociální pracovník', 359);
insert into position (id, title, employee_id) values (509, 'Sociální pracovník', 536);
insert into position (id, title, employee_id) values (510, 'Sociální pracovník', 598);
insert into position (id, title, employee_id) values (511, 'Sociální pracovník', 682);
insert into position (id, title, employee_id) values (512, 'Vedoucí sekce rízení lidských zdrojů', 486);
insert into position (id, title, employee_id) values (513, 'Manažer', 876);
insert into position (id, title, employee_id) values (514, 'Manažer', 793);
insert into position (id, title, employee_id) values (515, 'Sociální pracovník', 654);
insert into position (id, title, employee_id) values (516, 'Sociální pracovník', 800);
insert into position (id, title, employee_id) values (517, 'Sociální pracovník', 113);
insert into position (id, title, employee_id) values (518, 'Sociální pracovník', 942);
insert into position (id, title, employee_id) values (519, 'Sociální pracovník', 154);
insert into position (id, title, employee_id) values (520, 'Sociální pracovník', 907);
insert into position (id, title, employee_id) values (521, 'Sociální pracovník', 367);
insert into position (id, title, employee_id) values (522, 'Sociální pracovník', 101);
insert into position (id, title, employee_id) values (523, 'Sociální pracovník', 811);
insert into position (id, title, employee_id) values (524, 'Sociální pracovník', 117);
insert into position (id, title, employee_id) values (525, 'Sociální pracovník', 998);
insert into position (id, title, employee_id) values (526, 'Sociální pracovník', 645);
insert into position (id, title, employee_id) values (527, 'Sociální pracovník', 89);
insert into position (id, title, employee_id) values (528, 'Pracovník v sociálních službách', 295);
insert into position (id, title, employee_id) values (529, 'Sociální pracovník', 274);
insert into position (id, title, employee_id) values (530, 'Správce IT', 867);
insert into position (id, title, employee_id) values (531, 'Sociální pracovník', 451);
insert into position (id, title, employee_id) values (532, 'Sociální pracovník', 777);
insert into position (id, title, employee_id) values (533, 'Sociální pracovník', 463);
insert into position (id, title, employee_id) values (534, 'Sociální pracovník', 136);
insert into position (id, title, employee_id) values (535, 'Sociální pracovník', 582);
insert into position (id, title, employee_id) values (536, 'Sociální pracovník', 95);
insert into position (id, title, employee_id) values (537, 'Sociální pracovník', 170);
insert into position (id, title, employee_id) values (538, 'Sociální pracovník', 508);
insert into position (id, title, employee_id) values (539, 'Sociální pracovník', 203);
insert into position (id, title, employee_id) values (540, 'Sociální pracovník', 941);
insert into position (id, title, employee_id) values (541, 'Sociální pracovník', 951);
insert into position (id, title, employee_id) values (542, 'Sociální pracovník', 723);
insert into position (id, title, employee_id) values (543, 'Sociální pracovník', 231);
insert into position (id, title, employee_id) values (544, 'Sociální pracovník', 352);
insert into position (id, title, employee_id) values (545, 'Sociální pracovník', 406);
insert into position (id, title, employee_id) values (546, 'Sociální pracovník', 52);
insert into position (id, title, employee_id) values (547, 'Sociální pracovník', 821);
insert into position (id, title, employee_id) values (548, 'Personalista', 421);
insert into position (id, title, employee_id) values (549, 'Sociální pracovník', 980);
insert into position (id, title, employee_id) values (550, 'Sociální pracovník', 917);
insert into position (id, title, employee_id) values (551, 'Sociální pracovník', 529);
insert into position (id, title, employee_id) values (552, 'Sociální pracovník', 566);
insert into position (id, title, employee_id) values (553, 'Sociální pracovník', 316);
insert into position (id, title, employee_id) values (554, 'Pracovník v sociálních službách', 205);
insert into position (id, title, employee_id) values (555, 'Sociální pracovník', 217);
insert into position (id, title, employee_id) values (556, 'Sociální pracovník', 51);
insert into position (id, title, employee_id) values (557, 'Personalista', 478);
insert into position (id, title, employee_id) values (558, 'Vedoucí sekce rízení lidských zdrojů', 528);
insert into position (id, title, employee_id) values (559, 'Psychiatr', 509);
insert into position (id, title, employee_id) values (560, 'Sociální pracovník', 200);
insert into position (id, title, employee_id) values (561, 'Sociální pracovník', 369);
insert into position (id, title, employee_id) values (562, 'Sociální pracovník', 643);
insert into position (id, title, employee_id) values (563, 'Sociální pracovník', 550);
insert into position (id, title, employee_id) values (564, 'Sociální pracovník', 190);
insert into position (id, title, employee_id) values (565, 'Sociální pracovník', 233);
insert into position (id, title, employee_id) values (566, 'Sociální pracovník', 489);
insert into position (id, title, employee_id) values (567, 'Sociální pracovník', 585);
insert into position (id, title, employee_id) values (568, 'Vedoucí sekce rízení lidských zdrojů', 902);
insert into position (id, title, employee_id) values (569, 'Sociální pracovník', 184);
insert into position (id, title, employee_id) values (570, 'Sociální pracovník', 99);
insert into position (id, title, employee_id) values (571, 'Psychiatr', 623);
insert into position (id, title, employee_id) values (572, 'Sociální pracovník', 352);
insert into position (id, title, employee_id) values (573, 'Sociální pracovník', 159);
insert into position (id, title, employee_id) values (574, 'Sociální pracovník', 128);
insert into position (id, title, employee_id) values (575, 'Vedoucí sekce rízení lidských zdrojů', 420);
insert into position (id, title, employee_id) values (576, 'Sociální pracovník', 294);
insert into position (id, title, employee_id) values (577, 'Sociální pracovník', 543);
insert into position (id, title, employee_id) values (578, 'Sociální pracovník', 466);
insert into position (id, title, employee_id) values (579, 'Pracovník v sociálních službách', 646);
insert into position (id, title, employee_id) values (580, 'Sociální pracovník', 584);
insert into position (id, title, employee_id) values (581, 'Sociální pracovník', 466);
insert into position (id, title, employee_id) values (582, 'Sociální pracovník', 374);
insert into position (id, title, employee_id) values (583, 'Vedoucí sekce rízení lidských zdrojů', 222);
insert into position (id, title, employee_id) values (584, 'Vedoucí sekce rízení lidských zdrojů', 401);
insert into position (id, title, employee_id) values (585, 'Sociální pracovník', 355);
insert into position (id, title, employee_id) values (586, 'Sociální pracovník', 422);
insert into position (id, title, employee_id) values (587, 'Vedoucí sekce rízení lidských zdrojů', 846);
insert into position (id, title, employee_id) values (588, 'Sociální pracovník', 976);
insert into position (id, title, employee_id) values (589, 'Sociální pracovník', 63);
insert into position (id, title, employee_id) values (590, 'Sociální pracovník', 14);
insert into position (id, title, employee_id) values (591, 'Vedoucí sekce rízení lidských zdrojů', 330);
insert into position (id, title, employee_id) values (592, 'Pracovník v sociálních službách', 554);
insert into position (id, title, employee_id) values (593, 'Sociální pracovník', 336);
insert into position (id, title, employee_id) values (594, 'Sociální pracovník', 990);
insert into position (id, title, employee_id) values (595, 'Sociální pracovník', 944);
insert into position (id, title, employee_id) values (596, 'Personalista', 321);
insert into position (id, title, employee_id) values (597, 'Sociální pracovník', 695);
insert into position (id, title, employee_id) values (598, 'Sociální pracovník', 310);
insert into position (id, title, employee_id) values (599, 'Pracovník v sociálních službách', 445);
insert into position (id, title, employee_id) values (600, 'Vedoucí sekce rízení lidských zdrojů', 338);
insert into position (id, title, employee_id) values (601, 'Sociální pracovník', 53);
insert into position (id, title, employee_id) values (602, 'Sociální pracovník', 278);
insert into position (id, title, employee_id) values (603, 'Sociální pracovník', 78);
insert into position (id, title, employee_id) values (604, 'Sociální pracovník', 866);
insert into position (id, title, employee_id) values (605, 'Sociální pracovník', 268);
insert into position (id, title, employee_id) values (606, 'Sociální pracovník', 752);
insert into position (id, title, employee_id) values (607, 'Sociální pracovník', 158);
insert into position (id, title, employee_id) values (608, 'Sociální pracovník', 763);
insert into position (id, title, employee_id) values (609, 'Sociální pracovník', 261);
insert into position (id, title, employee_id) values (610, 'Sociální pracovník', 110);
insert into position (id, title, employee_id) values (611, 'Psychiatr', 309);
insert into position (id, title, employee_id) values (612, 'Sociální pracovník', 974);
insert into position (id, title, employee_id) values (613, 'Sociální pracovník', 296);
insert into position (id, title, employee_id) values (614, 'Personalista', 11);
insert into position (id, title, employee_id) values (615, 'Sociální pracovník', 259);
insert into position (id, title, employee_id) values (616, 'Sociální pracovník', 100);
insert into position (id, title, employee_id) values (617, 'Správce IT', 704);
insert into position (id, title, employee_id) values (618, 'Sociální pracovník', 57);
insert into position (id, title, employee_id) values (619, 'Sociální pracovník', 867);
insert into position (id, title, employee_id) values (620, 'Sociální pracovník', 308);
insert into position (id, title, employee_id) values (621, 'Sociální pracovník', 900);
insert into position (id, title, employee_id) values (622, 'Sociální pracovník', 946);
insert into position (id, title, employee_id) values (623, 'Sociální pracovníkVšeobecná sestra', 117);
insert into position (id, title, employee_id) values (624, 'Sociální pracovník', 114);
insert into position (id, title, employee_id) values (625, 'Sociální pracovník', 875);
insert into position (id, title, employee_id) values (626, 'Personalista', 78);
insert into position (id, title, employee_id) values (627, 'Sociální pracovník', 608);
insert into position (id, title, employee_id) values (628, 'Sociální pracovník', 392);
insert into position (id, title, employee_id) values (629, 'Sociální pracovník', 507);
insert into position (id, title, employee_id) values (630, 'Sociální pracovník', 949);
insert into position (id, title, employee_id) values (631, 'Pracovník v sociálních službách', 97);
insert into position (id, title, employee_id) values (632, 'Sociální pracovník', 224);
insert into position (id, title, employee_id) values (633, 'Sociální pracovník', 868);
insert into position (id, title, employee_id) values (634, 'Sociální pracovník', 923);
insert into position (id, title, employee_id) values (635, 'Vedoucí sekce rízení lidských zdrojů', 339);
insert into position (id, title, employee_id) values (636, 'Sociální pracovník', 52);
insert into position (id, title, employee_id) values (637, 'Sociální pracovník', 123);
insert into position (id, title, employee_id) values (638, 'Sociální pracovník', 262);
insert into position (id, title, employee_id) values (639, 'Sociální pracovník', 90);
insert into position (id, title, employee_id) values (640, 'Sociální pracovník', 420);
insert into position (id, title, employee_id) values (641, 'Vedoucí sekce rízení lidských zdrojů', 791);
insert into position (id, title, employee_id) values (642, 'Psychiatr', 480);
insert into position (id, title, employee_id) values (643, 'Sociální pracovník', 611);
insert into position (id, title, employee_id) values (644, 'Sociální pracovník', 329);
insert into position (id, title, employee_id) values (645, 'Sociální pracovník', 728);
insert into position (id, title, employee_id) values (646, 'Sociální pracovník', 463);
insert into position (id, title, employee_id) values (647, 'Sociální pracovník', 382);
insert into position (id, title, employee_id) values (648, 'Pracovník v sociálních službách', 275);
insert into position (id, title, employee_id) values (649, 'Sociální pracovník', 664);
insert into position (id, title, employee_id) values (650, 'Sociální pracovník', 650);
insert into position (id, title, employee_id) values (651, 'Sociální pracovník', 450);
insert into position (id, title, employee_id) values (652, 'Sociální pracovník', 398);
insert into position (id, title, employee_id) values (653, 'Sociální pracovník', 581);
insert into position (id, title, employee_id) values (654, 'Psychiatr', 447);
insert into position (id, title, employee_id) values (655, 'Psychiatr', 151);
insert into position (id, title, employee_id) values (656, 'Sociální pracovník', 57);
insert into position (id, title, employee_id) values (657, 'Manažer', 257);
insert into position (id, title, employee_id) values (658, 'Sociální pracovník', 111);
insert into position (id, title, employee_id) values (659, 'Sociální pracovník', 235);
insert into position (id, title, employee_id) values (660, 'Sociální pracovník', 109);
insert into position (id, title, employee_id) values (661, 'Sociální pracovník', 176);
insert into position (id, title, employee_id) values (662, 'Sociální pracovník', 208);
insert into position (id, title, employee_id) values (663, 'Sociální pracovník', 345);
insert into position (id, title, employee_id) values (664, 'Sociální pracovník', 2);
insert into position (id, title, employee_id) values (665, 'Sociální pracovník', 762);
insert into position (id, title, employee_id) values (666, 'Sociální pracovník', 519);
insert into position (id, title, employee_id) values (667, 'Sociální pracovník', 104);
insert into position (id, title, employee_id) values (668, 'Personalista', 946);
insert into position (id, title, employee_id) values (669, 'Personalista', 351);
insert into position (id, title, employee_id) values (670, 'Správce IT', 35);
insert into position (id, title, employee_id) values (671, 'Správce IT', 883);
insert into position (id, title, employee_id) values (672, 'Správce IT', 24);
insert into position (id, title, employee_id) values (673, 'Sociální pracovník', 56);
insert into position (id, title, employee_id) values (674, 'Sociální pracovník', 202);
insert into position (id, title, employee_id) values (675, 'Sociální pracovník', 517);
insert into position (id, title, employee_id) values (676, 'Sociální pracovník', 710);
insert into position (id, title, employee_id) values (677, 'Sociální pracovník', 988);
insert into position (id, title, employee_id) values (678, 'Psychiatr', 351);
insert into position (id, title, employee_id) values (679, 'Sociální pracovník', 216);
insert into position (id, title, employee_id) values (680, 'Sociální pracovník', 154);
insert into position (id, title, employee_id) values (681, 'Sociální pracovník', 220);
insert into position (id, title, employee_id) values (682, 'Sociální pracovník', 789);
insert into position (id, title, employee_id) values (683, 'Sociální pracovník', 693);
insert into position (id, title, employee_id) values (684, 'Personalista', 986);
insert into position (id, title, employee_id) values (685, 'Sociální pracovník', 46);
insert into position (id, title, employee_id) values (686, 'Sociální pracovník', 143);
insert into position (id, title, employee_id) values (687, 'Sociální pracovníkVšeobecná sestra', 693);
insert into position (id, title, employee_id) values (688, 'Sociální pracovník', 799);
insert into position (id, title, employee_id) values (689, 'Sociální pracovník', 228);
insert into position (id, title, employee_id) values (690, 'Sociální pracovník', 933);
insert into position (id, title, employee_id) values (691, 'Sociální pracovník', 538);
insert into position (id, title, employee_id) values (692, 'Manažer', 506);
insert into position (id, title, employee_id) values (693, 'Sociální pracovník', 139);
insert into position (id, title, employee_id) values (694, 'Sociální pracovník', 177);
insert into position (id, title, employee_id) values (695, 'Sociální pracovník', 854);
insert into position (id, title, employee_id) values (696, 'Sociální pracovník', 328);
insert into position (id, title, employee_id) values (697, 'Sociální pracovník', 752);
insert into position (id, title, employee_id) values (698, 'Sociální pracovník', 136);
insert into position (id, title, employee_id) values (699, 'Sociální pracovník', 964);
insert into position (id, title, employee_id) values (700, 'Sociální pracovník', 856);
insert into position (id, title, employee_id) values (701, 'Sociální pracovník', 782);
insert into position (id, title, employee_id) values (702, 'Sociální pracovník', 501);
insert into position (id, title, employee_id) values (703, 'Sociální pracovník', 887);
insert into position (id, title, employee_id) values (704, 'Sociální pracovník', 985);
insert into position (id, title, employee_id) values (705, 'Psychiatr', 150);
insert into position (id, title, employee_id) values (706, 'Sociální pracovník', 686);
insert into position (id, title, employee_id) values (707, 'Sociální pracovník', 654);
insert into position (id, title, employee_id) values (708, 'Sociální pracovník', 834);
insert into position (id, title, employee_id) values (709, 'Sociální pracovníkVšeobecná sestra', 563);
insert into position (id, title, employee_id) values (710, 'Sociální pracovník', 193);
insert into position (id, title, employee_id) values (711, 'Sociální pracovník', 704);
insert into position (id, title, employee_id) values (712, 'Sociální pracovník', 633);
insert into position (id, title, employee_id) values (713, 'Sociální pracovník', 934);
insert into position (id, title, employee_id) values (714, 'Sociální pracovník', 546);
insert into position (id, title, employee_id) values (715, 'Sociální pracovník', 876);
insert into position (id, title, employee_id) values (716, 'Sociální pracovník', 589);
insert into position (id, title, employee_id) values (717, 'Pracovník v sociálních službách', 82);
insert into position (id, title, employee_id) values (718, 'Sociální pracovník', 291);
insert into position (id, title, employee_id) values (719, 'Sociální pracovník', 476);
insert into position (id, title, employee_id) values (720, 'Sociální pracovník', 121);
insert into position (id, title, employee_id) values (721, 'Sociální pracovník', 742);
insert into position (id, title, employee_id) values (722, 'Sociální pracovník', 866);
insert into position (id, title, employee_id) values (723, 'Sociální pracovník', 96);
insert into position (id, title, employee_id) values (724, 'Sociální pracovník', 991);
insert into position (id, title, employee_id) values (725, 'Sociální pracovník', 172);
insert into position (id, title, employee_id) values (726, 'Sociální pracovník', 10);
insert into position (id, title, employee_id) values (727, 'Sociální pracovník', 361);
insert into position (id, title, employee_id) values (728, 'Sociální pracovník', 574);
insert into position (id, title, employee_id) values (729, 'Sociální pracovník', 773);
insert into position (id, title, employee_id) values (730, 'Manažer', 645);
insert into position (id, title, employee_id) values (731, 'Sociální pracovník', 265);
insert into position (id, title, employee_id) values (732, 'Sociální pracovník', 137);
insert into position (id, title, employee_id) values (733, 'Sociální pracovníkVšeobecná sestra', 762);
insert into position (id, title, employee_id) values (734, 'Sociální pracovník', 789);
insert into position (id, title, employee_id) values (735, 'Sociální pracovník', 903);
insert into position (id, title, employee_id) values (736, 'Sociální pracovník', 361);
insert into position (id, title, employee_id) values (737, 'Sociální pracovník', 286);
insert into position (id, title, employee_id) values (738, 'Sociální pracovník', 51);
insert into position (id, title, employee_id) values (739, 'Sociální pracovník', 181);
insert into position (id, title, employee_id) values (740, 'Personalista', 444);
insert into position (id, title, employee_id) values (741, 'Sociální pracovník', 763);
insert into position (id, title, employee_id) values (742, 'Sociální pracovník', 812);
insert into position (id, title, employee_id) values (743, 'Sociální pracovník', 898);
insert into position (id, title, employee_id) values (744, 'Sociální pracovník', 83);
insert into position (id, title, employee_id) values (745, 'Správce IT', 51);
insert into position (id, title, employee_id) values (746, 'Sociální pracovník', 69);
insert into position (id, title, employee_id) values (747, 'Sociální pracovník', 274);
insert into position (id, title, employee_id) values (748, 'Sociální pracovník', 753);
insert into position (id, title, employee_id) values (749, 'Sociální pracovník', 661);
insert into position (id, title, employee_id) values (750, 'Sociální pracovník', 247);
insert into position (id, title, employee_id) values (751, 'Sociální pracovník', 877);
insert into position (id, title, employee_id) values (752, 'Pracovník v sociálních službách', 60);
insert into position (id, title, employee_id) values (753, 'Personalista', 753);
insert into position (id, title, employee_id) values (754, 'Sociální pracovník', 301);
insert into position (id, title, employee_id) values (755, 'Sociální pracovník', 720);
insert into position (id, title, employee_id) values (756, 'Psychiatr', 525);
insert into position (id, title, employee_id) values (757, 'Sociální pracovník', 982);
insert into position (id, title, employee_id) values (758, 'Sociální pracovník', 32);
insert into position (id, title, employee_id) values (759, 'Vedoucí sekce rízení lidských zdrojů', 28);
insert into position (id, title, employee_id) values (760, 'Sociální pracovník', 853);
insert into position (id, title, employee_id) values (761, 'Sociální pracovník', 248);
insert into position (id, title, employee_id) values (762, 'Sociální pracovník', 514);
insert into position (id, title, employee_id) values (763, 'Sociální pracovník', 365);
insert into position (id, title, employee_id) values (764, 'Sociální pracovník', 499);
insert into position (id, title, employee_id) values (765, 'Sociální pracovník', 970);
insert into position (id, title, employee_id) values (766, 'Sociální pracovník', 935);
insert into position (id, title, employee_id) values (767, 'Sociální pracovník', 202);
insert into position (id, title, employee_id) values (768, 'Sociální pracovník', 550);
insert into position (id, title, employee_id) values (769, 'Sociální pracovník', 89);
insert into position (id, title, employee_id) values (770, 'Správce IT', 16);
insert into position (id, title, employee_id) values (771, 'Sociální pracovník', 48);
insert into position (id, title, employee_id) values (772, 'Sociální pracovník', 143);
insert into position (id, title, employee_id) values (773, 'Sociální pracovník', 856);
insert into position (id, title, employee_id) values (774, 'Sociální pracovník', 960);
insert into position (id, title, employee_id) values (775, 'Sociální pracovník', 721);
insert into position (id, title, employee_id) values (776, 'Sociální pracovníkVšeobecná sestra', 778);
insert into position (id, title, employee_id) values (777, 'Sociální pracovník', 610);
insert into position (id, title, employee_id) values (778, 'Sociální pracovník', 961);
insert into position (id, title, employee_id) values (779, 'Sociální pracovník', 186);
insert into position (id, title, employee_id) values (780, 'Sociální pracovník', 676);
insert into position (id, title, employee_id) values (781, 'Sociální pracovník', 732);
insert into position (id, title, employee_id) values (782, 'Sociální pracovník', 999);
insert into position (id, title, employee_id) values (783, 'Sociální pracovník', 797);
insert into position (id, title, employee_id) values (784, 'Sociální pracovník', 331);
insert into position (id, title, employee_id) values (785, 'Sociální pracovník', 465);
insert into position (id, title, employee_id) values (786, 'Sociální pracovník', 251);
insert into position (id, title, employee_id) values (787, 'Sociální pracovník', 44);
insert into position (id, title, employee_id) values (788, 'Manažer', 716);
insert into position (id, title, employee_id) values (789, 'Sociální pracovník', 385);
insert into position (id, title, employee_id) values (790, 'Sociální pracovník', 415);
insert into position (id, title, employee_id) values (791, 'Pracovník v sociálních službách', 495);
insert into position (id, title, employee_id) values (792, 'Sociální pracovník', 600);
insert into position (id, title, employee_id) values (793, 'Sociální pracovník', 477);
insert into position (id, title, employee_id) values (794, 'Sociální pracovník', 525);
insert into position (id, title, employee_id) values (795, 'Sociální pracovník', 670);
insert into position (id, title, employee_id) values (796, 'Sociální pracovník', 550);
insert into position (id, title, employee_id) values (797, 'Pracovník v sociálních službách', 59);
insert into position (id, title, employee_id) values (798, 'Sociální pracovník', 347);
insert into position (id, title, employee_id) values (799, 'Sociální pracovník', 373);
insert into position (id, title, employee_id) values (800, 'Sociální pracovník', 401);
insert into position (id, title, employee_id) values (801, 'Sociální pracovník', 855);
insert into position (id, title, employee_id) values (802, 'Personalista', 558);
insert into position (id, title, employee_id) values (803, 'Sociální pracovník', 284);
insert into position (id, title, employee_id) values (804, 'Sociální pracovník', 206);
insert into position (id, title, employee_id) values (805, 'Sociální pracovník', 976);
insert into position (id, title, employee_id) values (806, 'Psychiatr', 687);
insert into position (id, title, employee_id) values (807, 'Sociální pracovník', 563);
insert into position (id, title, employee_id) values (808, 'Sociální pracovník', 538);
insert into position (id, title, employee_id) values (809, 'Sociální pracovník', 567);
insert into position (id, title, employee_id) values (810, 'Sociální pracovník', 292);
insert into position (id, title, employee_id) values (811, 'Sociální pracovník', 32);
insert into position (id, title, employee_id) values (812, 'Sociální pracovník', 923);
insert into position (id, title, employee_id) values (813, 'Vedoucí sekce rízení lidských zdrojů', 436);
insert into position (id, title, employee_id) values (814, 'Sociální pracovník', 757);
insert into position (id, title, employee_id) values (815, 'Sociální pracovník', 117);
insert into position (id, title, employee_id) values (816, 'Sociální pracovník', 133);
insert into position (id, title, employee_id) values (817, 'Sociální pracovník', 889);
insert into position (id, title, employee_id) values (818, 'Sociální pracovník', 701);
insert into position (id, title, employee_id) values (819, 'Sociální pracovník', 711);
insert into position (id, title, employee_id) values (820, 'Sociální pracovník', 372);
insert into position (id, title, employee_id) values (821, 'Manažer', 75);
insert into position (id, title, employee_id) values (822, 'Psychiatr', 497);
insert into position (id, title, employee_id) values (823, 'Sociální pracovník', 259);
insert into position (id, title, employee_id) values (824, 'Sociální pracovník', 64);
insert into position (id, title, employee_id) values (825, 'Psychiatr', 530);
insert into position (id, title, employee_id) values (826, 'Sociální pracovník', 842);
insert into position (id, title, employee_id) values (827, 'Sociální pracovník', 237);
insert into position (id, title, employee_id) values (828, 'Sociální pracovník', 525);
insert into position (id, title, employee_id) values (829, 'Sociální pracovník', 56);
insert into position (id, title, employee_id) values (830, 'Sociální pracovník', 750);
insert into position (id, title, employee_id) values (831, 'Sociální pracovník', 540);
insert into position (id, title, employee_id) values (832, 'Sociální pracovník', 495);
insert into position (id, title, employee_id) values (833, 'Sociální pracovník', 878);
insert into position (id, title, employee_id) values (834, 'Sociální pracovník', 661);
insert into position (id, title, employee_id) values (835, 'Sociální pracovník', 731);
insert into position (id, title, employee_id) values (836, 'Sociální pracovník', 716);
insert into position (id, title, employee_id) values (837, 'Pracovník v sociálních službách', 670);
insert into position (id, title, employee_id) values (838, 'Sociální pracovník', 993);
insert into position (id, title, employee_id) values (839, 'Sociální pracovník', 640);
insert into position (id, title, employee_id) values (840, 'Sociální pracovník', 537);
insert into position (id, title, employee_id) values (841, 'Personalista', 392);
insert into position (id, title, employee_id) values (842, 'Sociální pracovník', 551);
insert into position (id, title, employee_id) values (843, 'Sociální pracovník', 482);
insert into position (id, title, employee_id) values (844, 'Správce IT', 560);
insert into position (id, title, employee_id) values (845, 'Sociální pracovník', 711);
insert into position (id, title, employee_id) values (846, 'Sociální pracovník', 172);
insert into position (id, title, employee_id) values (847, 'Sociální pracovníkVšeobecná sestra', 181);
insert into position (id, title, employee_id) values (848, 'Personalista', 240);
insert into position (id, title, employee_id) values (849, 'Sociální pracovník', 988);
insert into position (id, title, employee_id) values (850, 'Sociální pracovník', 633);
insert into position (id, title, employee_id) values (851, 'Sociální pracovník', 715);
insert into position (id, title, employee_id) values (852, 'Sociální pracovník', 717);
insert into position (id, title, employee_id) values (853, 'Sociální pracovník', 572);
insert into position (id, title, employee_id) values (854, 'Sociální pracovník', 43);
insert into position (id, title, employee_id) values (855, 'Sociální pracovník', 312);
insert into position (id, title, employee_id) values (856, 'Správce IT', 214);
insert into position (id, title, employee_id) values (857, 'Sociální pracovníkVšeobecná sestra', 891);
insert into position (id, title, employee_id) values (858, 'Sociální pracovník', 984);
insert into position (id, title, employee_id) values (859, 'Psychiatr', 313);
insert into position (id, title, employee_id) values (860, 'Sociální pracovník', 996);
insert into position (id, title, employee_id) values (861, 'Sociální pracovník', 7);
insert into position (id, title, employee_id) values (862, 'Sociální pracovník', 982);
insert into position (id, title, employee_id) values (863, 'Sociální pracovník', 539);
insert into position (id, title, employee_id) values (864, 'Sociální pracovník', 593);
insert into position (id, title, employee_id) values (865, 'Správce IT', 810);
insert into position (id, title, employee_id) values (866, 'Správce IT', 904);
insert into position (id, title, employee_id) values (867, 'Personalista', 680);
insert into position (id, title, employee_id) values (868, 'Sociální pracovník', 155);
insert into position (id, title, employee_id) values (869, 'Sociální pracovník', 555);
insert into position (id, title, employee_id) values (870, 'Sociální pracovník', 438);
insert into position (id, title, employee_id) values (871, 'Sociální pracovník', 548);
insert into position (id, title, employee_id) values (872, 'Sociální pracovník', 782);
insert into position (id, title, employee_id) values (873, 'Sociální pracovník', 484);
insert into position (id, title, employee_id) values (874, 'Sociální pracovník', 277);
insert into position (id, title, employee_id) values (875, 'Sociální pracovník', 708);
insert into position (id, title, employee_id) values (876, 'Sociální pracovník', 469);
insert into position (id, title, employee_id) values (877, 'Sociální pracovník', 438);
insert into position (id, title, employee_id) values (878, 'Sociální pracovník', 681);
insert into position (id, title, employee_id) values (879, 'Vedoucí sekce rízení lidských zdrojů', 527);
insert into position (id, title, employee_id) values (880, 'Sociální pracovník', 138);
insert into position (id, title, employee_id) values (881, 'Sociální pracovník', 469);
insert into position (id, title, employee_id) values (882, 'Sociální pracovník', 642);
insert into position (id, title, employee_id) values (883, 'Sociální pracovník', 125);
insert into position (id, title, employee_id) values (884, 'Sociální pracovník', 966);
insert into position (id, title, employee_id) values (885, 'Sociální pracovník', 824);
insert into position (id, title, employee_id) values (886, 'Sociální pracovník', 837);
insert into position (id, title, employee_id) values (887, 'Sociální pracovník', 275);
insert into position (id, title, employee_id) values (888, 'Sociální pracovník', 862);
insert into position (id, title, employee_id) values (889, 'Sociální pracovník', 604);
insert into position (id, title, employee_id) values (890, 'Vedoucí sekce rízení lidských zdrojů', 320);
insert into position (id, title, employee_id) values (891, 'Sociální pracovník', 4);
insert into position (id, title, employee_id) values (892, 'Sociální pracovník', 955);
insert into position (id, title, employee_id) values (893, 'Sociální pracovník', 917);
insert into position (id, title, employee_id) values (894, 'Sociální pracovník', 131);
insert into position (id, title, employee_id) values (895, 'Sociální pracovník', 112);
insert into position (id, title, employee_id) values (896, 'Sociální pracovník', 184);
insert into position (id, title, employee_id) values (897, 'Sociální pracovník', 458);
insert into position (id, title, employee_id) values (898, 'Sociální pracovník', 471);
insert into position (id, title, employee_id) values (899, 'Psychiatr', 39);
insert into position (id, title, employee_id) values (900, 'Sociální pracovník', 202);
insert into position (id, title, employee_id) values (901, 'Personalista', 435);
insert into position (id, title, employee_id) values (902, 'Sociální pracovník', 767);
insert into position (id, title, employee_id) values (903, 'Sociální pracovník', 759);
insert into position (id, title, employee_id) values (904, 'Sociální pracovník', 845);
insert into position (id, title, employee_id) values (905, 'Sociální pracovník', 669);
insert into position (id, title, employee_id) values (906, 'Vedoucí sekce rízení lidských zdrojů', 994);
insert into position (id, title, employee_id) values (907, 'Správce IT', 281);
insert into position (id, title, employee_id) values (908, 'Sociální pracovník', 357);
insert into position (id, title, employee_id) values (909, 'Sociální pracovník', 448);
insert into position (id, title, employee_id) values (910, 'Sociální pracovník', 212);
insert into position (id, title, employee_id) values (911, 'Psychiatr', 879);
insert into position (id, title, employee_id) values (912, 'Sociální pracovník', 855);
insert into position (id, title, employee_id) values (913, 'Sociální pracovník', 685);
insert into position (id, title, employee_id) values (914, 'Sociální pracovník', 406);
insert into position (id, title, employee_id) values (915, 'Sociální pracovník', 15);
insert into position (id, title, employee_id) values (916, 'Sociální pracovník', 655);
insert into position (id, title, employee_id) values (917, 'Sociální pracovníkVšeobecná sestra', 403);
insert into position (id, title, employee_id) values (918, 'Sociální pracovník', 139);
insert into position (id, title, employee_id) values (919, 'Sociální pracovník', 413);
insert into position (id, title, employee_id) values (920, 'Sociální pracovník', 485);
insert into position (id, title, employee_id) values (921, 'Sociální pracovník', 852);
insert into position (id, title, employee_id) values (922, 'Sociální pracovník', 951);
insert into position (id, title, employee_id) values (923, 'Sociální pracovník', 799);
insert into position (id, title, employee_id) values (924, 'Sociální pracovník', 966);
insert into position (id, title, employee_id) values (925, 'Sociální pracovník', 166);
insert into position (id, title, employee_id) values (926, 'Sociální pracovník', 448);
insert into position (id, title, employee_id) values (927, 'Sociální pracovník', 137);
insert into position (id, title, employee_id) values (928, 'Sociální pracovník', 358);
insert into position (id, title, employee_id) values (929, 'Personalista', 763);
insert into position (id, title, employee_id) values (930, 'Sociální pracovník', 523);
insert into position (id, title, employee_id) values (931, 'Sociální pracovník', 160);
insert into position (id, title, employee_id) values (932, 'Sociální pracovník', 535);
insert into position (id, title, employee_id) values (933, 'Sociální pracovník', 12);
insert into position (id, title, employee_id) values (934, 'Sociální pracovník', 939);
insert into position (id, title, employee_id) values (935, 'Sociální pracovník', 115);
insert into position (id, title, employee_id) values (936, 'Sociální pracovník', 21);
insert into position (id, title, employee_id) values (937, 'Sociální pracovník', 344);
insert into position (id, title, employee_id) values (938, 'Vedoucí sekce rízení lidských zdrojů', 240);
insert into position (id, title, employee_id) values (939, 'Sociální pracovník', 613);
insert into position (id, title, employee_id) values (940, 'Sociální pracovník', 424);
insert into position (id, title, employee_id) values (941, 'Sociální pracovník', 115);
insert into position (id, title, employee_id) values (942, 'Sociální pracovník', 866);
insert into position (id, title, employee_id) values (943, 'Psychiatr', 227);
insert into position (id, title, employee_id) values (944, 'Sociální pracovník', 964);
insert into position (id, title, employee_id) values (945, 'Sociální pracovník', 197);
insert into position (id, title, employee_id) values (946, 'Sociální pracovník', 33);
insert into position (id, title, employee_id) values (947, 'Sociální pracovník', 103);
insert into position (id, title, employee_id) values (948, 'Sociální pracovník', 424);
insert into position (id, title, employee_id) values (949, 'Sociální pracovník', 124);
insert into position (id, title, employee_id) values (950, 'Sociální pracovník', 129);
insert into position (id, title, employee_id) values (951, 'Sociální pracovník', 526);
insert into position (id, title, employee_id) values (952, 'Sociální pracovník', 5);
insert into position (id, title, employee_id) values (953, 'Sociální pracovník', 861);
insert into position (id, title, employee_id) values (954, 'Sociální pracovník', 926);
insert into position (id, title, employee_id) values (955, 'Sociální pracovník', 927);
insert into position (id, title, employee_id) values (956, 'Sociální pracovník', 2);
insert into position (id, title, employee_id) values (957, 'Sociální pracovník', 658);
insert into position (id, title, employee_id) values (958, 'Sociální pracovník', 983);
insert into position (id, title, employee_id) values (959, 'Personalista', 335);
insert into position (id, title, employee_id) values (960, 'Sociální pracovník', 697);
insert into position (id, title, employee_id) values (961, 'Sociální pracovník', 190);
insert into position (id, title, employee_id) values (962, 'Sociální pracovník', 558);
insert into position (id, title, employee_id) values (963, 'Sociální pracovník', 548);
insert into position (id, title, employee_id) values (964, 'Manažer', 45);
insert into position (id, title, employee_id) values (965, 'Sociální pracovník', 787);
insert into position (id, title, employee_id) values (966, 'Sociální pracovník', 562);
insert into position (id, title, employee_id) values (967, 'Sociální pracovník', 19);
insert into position (id, title, employee_id) values (968, 'Sociální pracovník', 712);
insert into position (id, title, employee_id) values (969, 'Sociální pracovník', 840);
insert into position (id, title, employee_id) values (970, 'Sociální pracovník', 420);
insert into position (id, title, employee_id) values (971, 'Sociální pracovník', 145);
insert into position (id, title, employee_id) values (972, 'Sociální pracovník', 626);
insert into position (id, title, employee_id) values (973, 'Sociální pracovník', 275);
insert into position (id, title, employee_id) values (974, 'Sociální pracovník', 591);
insert into position (id, title, employee_id) values (975, 'Sociální pracovník', 349);
insert into position (id, title, employee_id) values (976, 'Sociální pracovník', 28);
insert into position (id, title, employee_id) values (977, 'Sociální pracovník', 631);
insert into position (id, title, employee_id) values (978, 'Vedoucí sekce rízení lidských zdrojů', 933);
insert into position (id, title, employee_id) values (979, 'Sociální pracovník', 729);
insert into position (id, title, employee_id) values (980, 'Sociální pracovník', 158);
insert into position (id, title, employee_id) values (981, 'Sociální pracovník', 701);
insert into position (id, title, employee_id) values (982, 'Sociální pracovník', 676);
insert into position (id, title, employee_id) values (983, 'Sociální pracovník', 383);
insert into position (id, title, employee_id) values (984, 'Sociální pracovník', 686);
insert into position (id, title, employee_id) values (985, 'Sociální pracovník', 974);
insert into position (id, title, employee_id) values (986, 'Sociální pracovník', 674);
insert into position (id, title, employee_id) values (987, 'Sociální pracovník', 549);
insert into position (id, title, employee_id) values (988, 'Sociální pracovník', 844);
insert into position (id, title, employee_id) values (989, 'Sociální pracovník', 122);
insert into position (id, title, employee_id) values (990, 'Sociální pracovník', 580);
insert into position (id, title, employee_id) values (991, 'Sociální pracovník', 467);
insert into position (id, title, employee_id) values (992, 'Sociální pracovník', 733);
insert into position (id, title, employee_id) values (993, 'Sociální pracovník', 34);
insert into position (id, title, employee_id) values (994, 'Sociální pracovníkVšeobecná sestra', 159);
insert into position (id, title, employee_id) values (995, 'Sociální pracovník', 643);
insert into position (id, title, employee_id) values (996, 'Sociální pracovník', 779);
insert into position (id, title, employee_id) values (997, 'Sociální pracovník', 323);
insert into position (id, title, employee_id) values (998, 'Sociální pracovník', 244);
insert into position (id, title, employee_id) values (999, 'Sociální pracovník', 146);
insert into position (id, title, employee_id) values (1000, 'Sociální pracovník', 822);
